### PR TITLE
Heavy modifications to the installer code base

### PR DESCRIPTION
**Pull request by nickjer**
- refactored methods into rake tasks
- abstracted out software collections requirement
- fixed issues with updating apps
  - added support if repo url changes
  - clobber previous assets (issues occur if we don't do this)
  - use rsync for speedup when copying
- added logic to skip tasks if unnecessary
- cleans up unused gems and npm packages
- don't change working directory, otherwise can't copy and paste
  commands
- added support to modify base uri
- added CHANGELOG.md and fleshed out README.md
- pulled out multitask capability and allow it to be specified by
  command line with `-m -j [NUMBER]` instead
- removed redundant `install.sh`
- allow user to override some values with environment variables

### CODE REVIEW

**Comment by brianmcmichael** [comment]
We need to discuss the rationale for these changes. There has been no discussion about the original script or the motivation behind this.

**Comment by nickjer** [comment]
Sure we can talk about this in Monday's group meeting

**Comment by treydock** [comment]
Sysadmin 2 cents, I'd advocate each app have its own install script, like bin/setup or common rake task that something like this repo can invoke.  This would mainly benefit packaging of each app as its own package.  Would leave each app's repo responsible for install steps.

**Comment by nickjer** [comment]
I believe Rails 4.2+ comes with a `bin/setup`, but we currently haven't modified it to meet our needs yet. Also we'd have to port this solution to the Node.js apps.

One downside of using a setup script is if any command during the setup fails, it will continue forward instead of stopping everything like in `rake`. So care would need to be taken when developing this script to exit upon any system command error.

Otherwise, I also advocate that each of the system apps come with their own setup script responsible for:

- checking / installing / purging dependencies
- cleaning / compiling assets
- cleaning logs / cache
- generating the restart file

This would remove the need to determine whether an app is Ruby (Rails) or Node.js in this installer app.

**Comment by brianmcmichael** [comment]
There are a lot of additional tasks now, many of them don't appear to work.

```
± |updates ?:1 ✗| → time scl enable rh-ruby22 -- rake -T -A  
rake /                                  # 
rake /var                               # 
rake /var/www                           # 
rake /var/www/ood                       # 
rake /var/www/ood/apps                  # 
rake /var/www/ood/apps/sys              # 
rake /var/www/ood/apps/sys/activejobs   # 
rake /var/www/ood/apps/sys/dashboard    # 
rake /var/www/ood/apps/sys/file-editor  # 
rake /var/www/ood/apps/sys/files        # 
rake /var/www/ood/apps/sys/myjobs       # 
rake /var/www/ood/apps/sys/shell        # 
rake active_jobs_assets_precompile      # 
rake active_jobs_bundle_install         # 
rake active_jobs_checkout               # 
rake build                              # Build all apps
rake build/activejobs                   # 
rake build/dashboard                    # 
rake build/file-editor                  # 
rake build/files                        # 
rake build/myjobs                       # 
rake build/shell                        # 
rake build:active_jobs                  # Build the app: 'activejobs'
rake build:all                          # 
rake build:dashboard                    # Build the app: 'dashboard'
rake build:file_editor                  # Build the app: 'file-editor'
rake build:files                        # Build the app: 'files'
rake build:my_jobs                      # Build the app: 'myjobs'
rake build:shell                        # Build the app: 'shell'
rake clean                              # Clean all apps
rake clean:active_jobs                  # Clean the app: 'activejobs'
rake clean:all                          # 
rake clean:dashboard                    # Clean the app: 'dashboard'
rake clean:file_editor                  # Clean the app: 'file-editor'
rake clean:files                        # Clean the app: 'files'
rake clean:my_jobs                      # Clean the app: 'myjobs'
rake clean:shell                        # Clean the app: 'shell'
rake dashboard_assets_precompile        # 
rake dashboard_bundle_install           # 
rake dashboard_checkout                 # 
rake default                            # 
rake file_editor_assets_precompile      # 
rake file_editor_bundle_install         # 
rake file_editor_checkout               # 
rake files_checkout                     # 
rake files_npm_install                  # 
rake install                            # Install all apps
rake install:active_jobs                # Install the app: 'activejobs'
rake install:all                        # 
rake install:dashboard                  # Install the app: 'dashboard'
rake install:file_editor                # Install the app: 'file-editor'
rake install:files                      # Install the app: 'files'
rake install:my_jobs                    # Install the app: 'myjobs'
rake install:shell                      # Install the app: 'shell'
rake my_jobs_assets_precompile          # 
rake my_jobs_bundle_install             # 
rake my_jobs_checkout                   # 
rake shell_checkout                     # 
rake shell_npm_install                  # 
```

**Comment by nickjer** [comment]
You should only call `rake -T` to see the user-specific tasks. It is similar to a `Makefile` where there is a task for every object file, but you would typically only call `make`, `make clean`, and a few others.

**Comment by brianmcmichael** [comment]
Compare with the corresponding output of the `master` script. The only difference between `-T` and `-T -A` is that `-T` hides the tasks without descriptions. They're still user-exposed.

```
± |master ?:2 ✗| → time rake -T -A              
rake build_apps_parallel   # Build all available apps in parallel
rake build_apps_serial     # Build all available apps in serial
rake default               # Build all available applications in parallel
rake deploy                # Copies the application to the deployment path
rake install               # Copies all application assets to the deployment path
rake install_activejobs    # Clone and build activejobs
rake install_dashboard     # Clone and build dashboard
rake install_file-editor   # Clone and build file-editor
rake install_files         # Clone and build files
rake install_myjobs        # Clone and build myjobs
rake install_shell         # Clone and build shell
rake update                # Update all available applications in parallel
rake update_activejobs     # Update and rebuild activejobs
rake update_apps_parallel  # Update all available apps in parallel
rake update_apps_serial    # Update all available apps in serial
rake update_dashboard      # Update and rebuild dashboard
rake update_file-editor    # Update and rebuild file-editor
rake update_files          # Update and rebuild files
rake update_myjobs         # Update and rebuild myjobs
rake update_shell          # Update and rebuild shell
```

**Comment by ericfranz** [comment]
So, for the dashboard, these are the build directions for OSC:

1. Checkout latest tag
2. **Copy OSC specific environment mods: `cp .env.local.osc .env.local`**
3. **Copy OSC specific initializer: `cp config/initializers/ood.rb.osc config/initializers/ood.rb`**
4. Bundle install
5. Rebuild assets
6. Touch restart
7. Deploy

There isn't a sensible place to put steps 2 and 3 in this script. So we won't yet be able to use this internally if we pull in this PR.

The two solutions to this problem are to have app specific installation scripts and remove configuration steps from the build.

**Comment by nickjer** [comment]
@brianmcmichael 

Right, I am not saying a user should never call `-T -A`. I am just saying that the tasks that a developer intends to expose to a user is displayed through only `-T`.

For example, in a Rails app:

```bash
bin/rake -T -A | wc
     73     448    4795

bin/rake -T | wc
     25     304    2731
```

That is a difference of 48 tasks.

You can see this behavior in Makefile's as well. Typically they have a task for every file in their project that needs to be compiled.

**Comment by brianmcmichael** [comment]
If you look at what the "hidden" tasks are, however, you'll note that they are basically just ways to perform specific actions of a certain type. Even though they aren't specifically documented, they're still intended for use.

```
rake db:migrate                         # Migrate the database (options: VERSION=x, VERBOSE=false, SCOPE=blog)
rake db:migrate:down                    # 
rake db:migrate:redo                    # 
rake db:migrate:reset                   # 
rake db:migrate:status                  # Display status of migrations
```

**Comment by nickjer** [comment]
@ericfranz 

For one of the centers, the most error-prone step in the installation occurred during the app installation. This means that we need a solution for this as soon as possible, since we have other centers installing OOD in the coming weeks.

I am all for having the apps build themselves, but what is the turnaround time for this? Can this be done for all the apps in the next few days, and have those app versions become the new default versions of the apps that we recommend all centers install?

**Comment by brianmcmichael** [comment]
The problem with having distributed scripts in all of these apps is that it becomes a lot of duplicated code across a lot of repos, when we update the process, all of the scripts will need to be updated. And we'd still need a general script like this to tie them all together.

**Comment by nickjer** [comment]
@brianmcmichael:

```sh
scl enable rh-ruby22 nodejs010 git19 -- rake build/dashboard
```

That does nothing because it already exists. That is one of the benefits of Rakefile and Makefile. It doesn't reproduce tasks unless something has changed. For directories it will only run the task if the directory doesn't exist.

**Comment by brianmcmichael** [comment]
This isn't a Makefile, though. It's a Rakefile, and we should be leveraging the Ruby scripting process instead of trying to create something that looks like C.

**Comment by nickjer** [comment]
That is how Rakefile works though. So I am leveraging Rakefile.

http://rake.rubyforge.org/doc/rakefile_rdoc.html#label-Directory+Tasks

**Pull request merged**
